services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgresdb
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./veterans
          target: /usr/src/app
    volumes:
     - ./veterans/coverage:/usr/src/app/coverage

  postgresdb:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - .env
  
