FROM node:22.11.0

WORKDIR /usr/src/app

COPY ./veterans/package.json ./veterans/package-lock.json ./

RUN npm ci && npm cache clean --force

COPY ./veterans .

COPY ./scripts/wait-schema-for-keystone.sh /usr/src/app/wait-schema-for-keystone.sh

RUN chmod +x /usr/src/app/wait-schema-for-keystone.sh

EXPOSE 3000

CMD ["npm", "run", "keystone:dev"]
