FROM node:22.11.0

WORKDIR /usr/src/app

COPY ./veterans/package.json ./veterans/package-lock.json ./

RUN npm ci && npm cache clean --force

RUN ls -l ./veterans

COPY ./veterans/schema.prisma ./

RUN npx prisma generate --schema=schema.prisma

COPY ./veterans .

EXPOSE 8000

CMD ["npm", "run", "next:dev"]
