services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - APOS_MONGODB_URI=mongodb://$MONGO_USER:$MONGO_PASSWORD@mongodb:27017/$MONGO_INITDB_DATABASE
    develop:
      watch:
        - action: sync
          path: ./veterans
          target: /usr/src/app

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
    restart: unless-stopped
    env_file:
      - .env

volumes:
  mongo-data:



  
