FROM node:22.11.0

WORKDIR /usr/src/app

COPY ./veterans/package.json ./veterans/package-lock.json ./

RUN npm ci && npm cache clean --force

COPY ./veterans .

EXPOSE 3000

# CMD ["sh", "-c", "npx prisma generate --schema=/usr/src/app/shared/schema.prisma && npm run next:dev"]

CMD ["npm", "run", "next:dev"]