FROM node:22.11.0

WORKDIR /usr/src/app

COPY ./veterans/package.json ./veterans/package-lock.json ./

RUN npm ci && npm cache clean --force

COPY ./veterans .

COPY ./veterans/wait-for-schema.sh /usr/src/app/wait-for-schema.sh

RUN chmod +x /usr/src/app/wait-for-schema.sh

CMD ["sh", "-c", "npm run keystone:dev & /usr/src/app/wait-for-schema.sh && cp schema.prisma /usr/src/app/schema.prisma && tail -f /dev/null"]
