services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - APOS_MONGODB_URI=mongodb://$MONGO_USER:$MONGO_PASSWORD@mongodb:27017/$MONGO_INITDB_DATABASE
    develop:
      watch:
        - action: sync
          path: ./veterans
          target: /usr/src/app

  postgresdb:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - .env

volumes:
  mongo-data:



  
