FROM node:22.11.0

WORKDIR /usr/src/app

COPY ./veterans/package.json ./veterans/package-lock.json ./

RUN npm ci && npm cache clean --force

COPY ./veterans .

CMD ["sh", "-c", "while [ ! -f schema.prisma ]; do echo 'Waiting for schema.prisma...'; sleep 1; done && npx prisma generate --schema=schema.prisma && npm run next:dev"]
