[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile.keystone"

[deploy]
startCommand = "./node_modules/.bin/keystone start"
healthcheckPath = "/api/graphql"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.env]
PORT = "3000"
NODE_ENV = "production" 