[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile.keystone"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.env]
NODE_ENV = "${{NODE_ENV}}"
PORT = "${{PORT}}"
DATABASE_URL = "${{DATABASE_URL}}"
SESSION_SECRET = "${{SESSION_SECRET}}"
