[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile.keystone"

[deploy]
startCommand = "/usr/src/app/start.sh"
healthcheckPath = "/api/graphql"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.env]
PORT = "3000"
NODE_ENV = "production"
# Make sure to link your PostgreSQL service in Railway dashboard
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
SESSION_SECRET = "your_actual_production_secret_minimum_32_chars_long_change_this" 