[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile.keystone"

[build.args]
PRODUCTION_DATABASE_URL = "${{PRODUCTION_DATABASE_URL}}"
SESSION_SECRET = "${{SESSION_SECRET}}"

[deploy]
startCommand = "/usr/src/app/start.sh"
healthcheckPath = "/api/graphql"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.env]
NODE_ENV = "production"
DATABASE_URL = "${{PRODUCTION_DATABASE_URL}}"
PRODUCTION_DATABASE_URL = "${{PRODUCTION_DATABASE_URL}}"
SESSION_SECRET = "${{SESSION_SECRET}}"
PORT = "3000" 