[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile.keystone"

[build.args]
SESSION_SECRET = "${{SESSION_SECRET}}"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10


[deploy.env]
NODE_ENV = "production"
PORT = "3000"
DATABASE_URL = "${{DATABASE_URL}}"
SESSION_SECRET = "${{SESSION_SECRET}}" 