[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile.keystone"
[build.args]
PRODUCTION_DATABASE_URL = "${{PRODUCTION_DATABASE_URL}}"
SESSION_SECRET = "${{SESSION_SECRET}}"

[deploy]
startCommand = "docker run -p $PORT:3000 my-keystone"
healthcheckPath = "/api/graphql"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.env]
NODE_ENV = "production"
PRODUCTION_DATABASE_URL = "${{PRODUCTION_DATABASE_URL}}"
SESSION_SECRET = "${{SESSION_SECRET}}" 