[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile.keystone"

[deploy]
startCommand = "npm run keystone:dev"
healthcheckPath = "/api/graphql"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.env]
PORT = "3000" 