[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile.keystone"

[build.args]
SESSION_SECRET = "${{SESSION_SECRET}}"

[deploy]
startCommand = "/usr/src/app/start.sh"
healthcheckPath = "/api/graphql"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckHeaders = { "Content-Type" = "application/json" }
healthcheckBody = { "query" = "query { __schema { types { name } } }" }

[deploy.env]
NODE_ENV = "production"
PORT = "3000"
DATABASE_URL = "${{DATABASE_URL}}"
SESSION_SECRET = "${{SESSION_SECRET}}" 