[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile.keystone"

[deploy]
startCommand = "/usr/src/app/start.sh"
healthcheckPath = "/api/graphql"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.env]
PORT = "3000"
NODE_ENV = "production"
# Use PRODUCTION_DATABASE_URL from .env file
DATABASE_URL = "${{PRODUCTION_DATABASE_URL}}"
SESSION_SECRET = "your_actual_production_secret_minimum_32_chars_long_change_this" 