name: CodeQuality

on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Run tests
      run: docker-compose run app npm run test
  e2e-test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Run tests
      run: docker-compose run app npm run e2e-test
  lint:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run tests
        run: docker-compose run app npm run lint

