name: CodeQuality

on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  docker-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Run hadolint
      run: docker run --rm -i hadolint/hadolint < Dockerfile

  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Copy .env file
      run: cp .env.example .env
    - name: Build app image
      run: docker compose build
    - name: Run tests
      run: docker compose run --rm app npm run test
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      with:
        args: > 
          -Dproject.settings=./sonar-project.properties
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  e2e-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Copy .env file
      run: cp .env.example .env
    - name: Build app image
      run: docker compose build
    - name: Run e2e tests
      run: docker compose run --rm app npm run e2e-test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Copy .env file
        run: cp .env.example .env
      - name: Build app image
        run: docker compose build
      - name: Run linters
        run: docker compose run --rm app npm run lint

