name: "Tests: E2E"

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  tests_e2e:
    timeout-minutes: 60
    name: Run end-to-end tests
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:27.2.0
        options: --privileged
        ports:
          - 3000:3000
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - uses: actions/checkout@v4

      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo usermod -aG docker $USER

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose-plugin
          docker compose version

      - name: Adding credentials to .env file
        run: |
          cp .env.example .env

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Start services using Docker Compose
        run: docker compose up -d --build

      - name: Install Dependencies
        run: docker compose exec app npm install

      - name: Install Playwright Browsers
        run: docker compose exec app npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          docker compose exec app npm run test:e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
