name: "Tests: E2E"
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  tests_e2e:
    timeout-minutes: 60
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install Dependencies
        run: npm ci

      # Set up Docker (Docker already pre-installed in most GitHub CI environments)
      # - name: Set up Docker
      # run: sudo apt-get update && sudo apt-get install -y docker-compose

      # Build Docker image for Playwright tests
      # - name: Build Docker image
      # run: docker build -t test:e2e .

      # Run Playwright tests inside Docker container
      - name: Run Playwright tests
        run: docker run test:e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
