name: Vercel Preview Deployment

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_CLI_TOKEN: ${{ secrets.VERCEL_CLI_TOKEN }}
  TEST_DATABASE_URL: ${{ secrets.DEVELOPMENT_DATABASE_URL }}
  NODE_ENV: 'test'

jobs:
  docker-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint Dockerfile.keystone
        run: docker run --rm -i hadolint/hadolint < Dockerfile.keystone

      - name: Lint Dockerfile.nextjs
        run: docker run --rm -i hadolint/hadolint < Dockerfile.nextjs

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: echo "DEVELOPMENT_DATABASE_URL=${{ secrets.DEVELOPMENT_DATABASE_URL }}" > veterans/.env

      - name: Build app image
        run: docker compose build

      - name: Run tests
        run: docker compose run --rm app-nextjs npm run test -- --coverage

      - name: Save coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: veterans/coverage/lcov.info

  e2e-tests:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "DEVELOPMENT_DATABASE_URL=${{ secrets.DEVELOPMENT_DATABASE_URL }}" > veterans/.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> veterans/.env

      - name: Docker starts services
        run: docker compose up -d --build

      - name: Install Playwright Browsers (app-keystone)
        run: docker compose exec app-keystone npx playwright install --with-deps

      - name: Run Playwright tests (app-keystone)
        run: |
          set -e  # Ensures failure stops the pipeline
          docker compose exec app-nextjs sh -c "npm run test:e2e -- e2e/keystone-test"

      - name: Install Playwright Browsers (app-nextjs)
        run: docker compose exec app-nextjs npx playwright install --with-deps

      - name: Run Playwright tests (app-nextjs)
        run: |
          set -e  # Ensures failure stops the pipeline
          docker compose exec app-nextjs sh -c "npm run test:e2e -- e2e/nextjs-test"

      - uses: actions/upload-artifact@v4
        if: ${{ success() }}
        with:
          name: playwright-report
          path: veterans/playwright-report/
          retention-days: 30

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: echo "DEVELOPMENT_DATABASE_URL=${{ secrets.DEVELOPMENT_DATABASE_URL }}" > veterans/.env

      - name: Build app image
        run: docker compose build

      - name: Run linters
        run: docker compose run --rm app-nextjs npm run lint

  sonarqube:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    needs: unit-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v4.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@v1.1.0
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  preview-deployment:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.url }}

    needs:
      - lint
      - unit-tests
      - e2e-tests
      - sonarqube

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Validate required secrets
        run: |
          if [ -z "$VERCEL_ORG_ID" ] || [ -z "$VERCEL_PROJECT_ID" ] || [ -z "$VERCEL_CLI_TOKEN" ] || [ -z "$TEST_DATABASE_URL" ]; then
            echo "::error::Required secrets VERCEL_ORG_ID, VERCEL_PROJECT_ID, VERCEL_CLI_TOKEN and TEST_DATABASE_URL must be set"
            exit 1
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.2'
          cache: 'npm'
          cache-dependency-path: './veterans/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: ./veterans

      - name: Run Keystone test build
        run: npm run keystone:test:build
        working-directory: ./veterans

      - name: Clean node_modules/.prisma
        run: |
          if [ -d "node_modules/.prisma" ]; then
            rm -rf node_modules/.prisma
            echo "Cleaned .prisma directory"
          fi
        working-directory: ./veterans

      - name: Add binaryTargets to schema.prisma
        run: |
          if ! node scripts/add-binary-targets.js; then
            echo "::error::Failed to add binary targets to schema.prisma"
            exit 1
          fi

      - name: Generate Prisma Client
        run: |
          if ! npx prisma generate; then
            echo "::error::Failed to generate Prisma Client"
            exit 1
          fi
        working-directory: ./veterans

      - name: Pull Vercel Environment
        run: |
          npx vercel pull --yes --environment=preview --token="$VERCEL_CLI_TOKEN"
          echo "Vercel Environment pulled successfully."

      - name: Build project
        run: npx vercel build --yes --token="$VERCEL_CLI_TOKEN"
        timeout-minutes: 10
        working-directory: ./veterans

      - name: Copy Prisma binaries to Vercel deployment output
        run: |
          DEST_DIR=".vercel/output/functions/api/posts.func/node_modules/.prisma/client/"
          if [ ! -d "node_modules/.prisma/client/" ]; then
            echo "::error::Source Prisma client directory not found"
            exit 1
          fi
          mkdir -p "$DEST_DIR"
          if ! cp -r node_modules/.prisma/client/* "$DEST_DIR"; then
            echo "::error::Failed to copy Prisma binaries"
            exit 1
          fi
          echo "Successfully copied Prisma binaries to deployment output"
        working-directory: ./veterans

      - name: Deploy to Vercel
        id: deploy
        run: |
          if ! DEPLOYMENT_URL=$(npx vercel deploy --prebuilt --token="$VERCEL_CLI_TOKEN"); then
            echo "::error::Deployment failed"
            exit 1
          fi
          echo "url=$DEPLOYMENT_URL" >> "$GITHUB_OUTPUT"
          echo "Preview URL: $DEPLOYMENT_URL"
        working-directory: ./veterans
