name: Update Snapshots

on:
  workflow_dispatch:

jobs:
  update-snapshots:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "DEVELOPMENT_DATABASE_URL=${{ secrets.DEVELOPMENT_DATABASE_URL }}" > veterans/.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> veterans/.env

      - name: Docker starts services
        run: docker compose up -d --build

      - name: Install Playwright Browsers (app-nextjs)
        run: docker compose exec app-nextjs npx playwright install --with-deps
      - name: Run Playwright tests (app-nextjs)
        run: docker compose exec app-nextjs sh -c "npm run test:e2e -- e2e/nextjs-test --update-snapshots"

      - name: Upload snapshots as new artifact
        # if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-snapshots
          path: e2e/nextjs-test/screenshot-test.spec.ts-snapshots
          overwrite: true
          retention-days: 45
