name: Deploy to Vercel

on:
  workflow_dispatch:

jobs:
  deploy-preview:
    name: Deploy Preview
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: ./veterans # Specify the working directory here
        run: npm install

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Pull Vercel Environment
        working-directory: ./veterans
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_CLI_TOKEN }}

      - name: Build project
        working-directory: ./veterans
        run: vercel build --yes --token=${{ secrets.VERCEL_CLI_TOKEN }}

      - name: Deploy to Vercel
        id: deploy
        working-directory: ./veterans
        run: |
          DEPLOYMENT_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_CLI_TOKEN }})
          echo "deployment_url=$DEPLOYMENT_URL" >> $GITHUB_ENV

      - name: Upload Deployment Environment
        uses: actions/upload-artifact@v3
        with:
          name: preview-deployment
          path: preview-deployment.env

    env:
      CI_COMMIT_REF_SLUG: ${{ github.head_ref || github.ref_name }}
      CI_PROJECT_NAMESPACE: ${{ github.repository_owner }}
      CI_PIPELINE_SOURCE: workflow_dispatch
