name: Deploy to Vercel

on:
  workflow_dispatch:

jobs:
  deploy-preview:
    name: Deploy Preview
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./veterans

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.18.2"
          cache: "npm"
          cache-dependency-path: "./veterans/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Pull Vercel Environment
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_CLI_TOKEN }}

      - name: Build project
        run: vercel build --yes --token=${{ secrets.VERCEL_CLI_TOKEN }}
        timeout-minutes: 10

      - name: Deploy to Vercel
        id: deploy
        run: |
          # DEPLOYMENT_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_CLI_TOKEN }})
          # echo "deployment_url=$DEPLOYMENT_URL" >> $GITHUB_ENV

          if ! DEPLOYMENT_URL="$(vercel deploy --prebuilt --token="${{ secrets.VERCEL_CLI_TOKEN }}")"; then
            echo "::error::Deployment failed"
            exit 1
          fi
          echo "deployment_url=${DEPLOYMENT_URL}" >> $GITHUB_ENV
        timeout-minutes: 10

      - name: Upload Deployment Environment
        uses: actions/upload-artifact@v4
        with:
          name: preview-deployment
          path: preview-deployment.env

    env:
      CI_COMMIT_REF_SLUG: ${{ github.head_ref || github.ref_name }}
      CI_PROJECT_NAMESPACE: ${{ github.repository_owner }}
      CI_PIPELINE_SOURCE: workflow_dispatch
